on: [push]

jobs:
  __tests__:
    runs-on: ubuntu-latest
    name: Test for npm-publish
    steps:
      - name: Hello world action step
        id: hello
        uses: afeiship/action-npm-publish@master
        with:
          commit_pattern: 'Hello fei'
