on:
  push:
      branches:
        - master
jobs:
  __tests__:
    runs-on: ubuntu-latest
    name: Test for npm-publish
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Hello world action step
        id: hello
        uses: afeiship/action-npm-publish@master
        with: # All of theses inputs are optional
          tag_name: "v%s"
          tag_message: "v%s"
          commit_pattern: "^Release (\\S+)"
        env: # More info about the environment variables in the README
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} # You need to set this in your repo settings
